l=float(input("Enter length :"))
b=float(input("Enter breadth :"))
pr=2*(l+b)
print("*"*50)
print("\tlength:{}".format(l))
print("\tbreadth:{}".format(b))
print("\tPerimeter:{}".format(pr))
print("\tperimeter :%0.2f" %pr)
print("\tPerimeter :{}".format(round(pr,2)))
print("*"*50)
